name: azkar_app
description: تطبيق أذكار - مشروع Flutter skeleton
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.0
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.0
  provider: ^6.0.5
  share_plus: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/azkar.json
